version: '3.3'

services:

  postgres:
    image: postgres
    restart: always
    ports:
        - 5432:5432
    environment:
      POSTGRES_USER: dbuser
      POSTGRES_PASSWORD: pwd123
      POSTGRES_DB: demo-service

  keycloak:
    image: quay.io/keycloak/keycloak:latest
    container_name: keycloak
    restart: always
    ports:
      - 8403:8080
    volumes:
      - ./keycloak:/tmp
    environment:
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
      KEYCLOAK_IMPORT: /tmp/demo_realm.json -Dkeycloak.profile.feature.upload_scripts=enabled
      DB_VENDOR: h2


  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: zookeeper

  kafka:
    image: wurstmeister/kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 127.0.0.1
      KAFKA_ADVERTISED_PORT: 9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
